version: '3.1'

services:
  wordpress_kunte:
    container_name: wordpress_kunte
    image: wordpress
    restart: always
    ports:
      - 8000:80
    # environment:
    #   WORDPRESS_DB_HOST: db
    #   WORDPRESS_DB_USER: exampleuser
    #   WORDPRESS_DB_PASSWORD: examplepass
    #   WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress_kunte:/var/www/html

  wordpress_cuba:
    container_name: wordpress_cuba
    image: wordpress
    restart: always
    ports:
      - 9000:80
    # environment:
    #   WORDPRESS_DB_HOST: db
    #   WORDPRESS_DB_USER: exampleuser
    #   WORDPRESS_DB_PASSWORD: examplepass
    #   WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress_cuba:/var/www/html

  db:
    image: mysql:5.7
    container_name: mysql_kunte
    restart: always
    command: --innodb_use_native_aio=0 --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      # MYSQL_DATABASE: exampledb
      # MYSQL_USER: exampleuser
      # MYSQL_PASSWORD:  examplepass
      # MYSQL_RANDOM_ROOT_PASSWORD: '1'
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql

volumes:
  wordpress:
  db:
